// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {lambdaCalculusHighlighting} from "./highlight"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#SOVQPOOO[QPO'#C`QVQPOOO[QPO'#CfOOQO'#Cf'#CfOOQO'#C^'#C^OgQPO'#CeOOQO,58z,58zOOQO'#Ce'#CeOOQO-E6^-E6^OlQPO,59QOqQPO,59POOQO1G.l1G.lOOQO'#C_'#C_O[QPO1G.kOOQO7+$V7+$V",
  stateData: "v~OVOS~OWPO~OZRO]SO^TO~O]ZO~O[[O~O_]O~O",
  goto: "xZPP[adPPPPjsVUPR^R^ZQQORXQQVPQYRR_^VWPR^",
  nodeNames: "⚠ Script Lambda Dot",
  maxTerm: 15,
  propSources: [lambdaCalculusHighlighting],
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "!l~R[XYwYZ|]^|pqwxy!Ryz!W!O!P!]!c!}!b#T#o!b5s5t!g$I|$I}|$I}$JO|~|OV~~!ROW~~!WOZ~~!]O[~~!bO_~~!gO]~~!lO^~",
  tokenizers: [0],
  topRules: {"Script":[0,1]},
  tokenPrec: 0
})
