// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {lambdaCalculusHighlighting} from "./highlight"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!pOVQPOOOYQPO'#CdOOQO'#Cd'#CdOeQPO'#CcOOQO'#C^'#C^QVQPOOOOQO'#Cc'#CcOjQPO,59OOoQPO,58}OOQO-E6[-E6[OOQO1G.j1G.jOYQPO1G.iOOQO7+$T7+$T",
  stateData: "t~OTOS~OUSOXPOZQO[RO~OZWO~OYYO~O]ZO~O",
  goto: "pXPPYPPPP`jQTORXTSSOTQVPR[ZXUOPTZ",
  nodeNames: "⚠ Script",
  maxTerm: 13,
  propSources: [lambdaCalculusHighlighting],
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "!l~R[XYwYZ|]^|pqwxy!Ryz!W!O!P!]!c!}!b#T#o!b5s5t!g$I|$I}|$I}$JO|~|OT~~!ROU~~!WOX~~!]OY~~!bO]~~!gOZ~~!lO[~",
  tokenizers: [0],
  topRules: {"Script":[0,1]},
  tokenPrec: 0
})
